apiVersion: v1
kind: Service
metadata:
  name: client-1
spec:
  selector:
    app: client-1
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: client-2
spec:
  selector:
    app: client-2
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: client-3
spec:
  selector:
    app: client-3
  ports:
  - port: 5000
    targetPort: 5000
